"""Curated viewpoints. Plain data, so there is nothing to migrate."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Place:
    slug: str
    name: str
    country: str
    latitude: float
    longitude: float
    timezone: str
    note: str


PLACES: tuple[Place, ...] = (
    Place(
        "lofoten",
        "Reine, Lofoten",
        "Norway",
        67.9333,
        13.0833,
        "Europe/Oslo",
        "Midnight sun from late May to mid July.",
    ),
    Place(
        "trolltunga",
        "Trolltunga",
        "Norway",
        60.1242,
        6.7401,
        "Europe/Oslo",
        "The ledge faces east, so the light is best early.",
    ),
    Place(
        "preikestolen",
        "Preikestolen",
        "Norway",
        58.9864,
        6.1904,
        "Europe/Oslo",
        "A fjord below and a long walk up, so plan around sunset.",
    ),
    Place(
        "geiranger",
        "Geirangerfjord",
        "Norway",
        62.1010,
        7.2050,
        "Europe/Oslo",
        "Steep walls mean the sun leaves the water long before it sets.",
    ),
    Place(
        "alesund",
        "Ålesund",
        "Norway",
        62.4722,
        6.1495,
        "Europe/Oslo",
        "The view from Aksla faces west over the islands, so the town is backlit at sunset.",
    ),
    Place(
        "tromso",
        "Tromsø",
        "Norway",
        69.6492,
        18.9553,
        "Europe/Oslo",
        "Polar night from late November to mid January.",
    ),
    Place(
        "svalbard",
        "Longyearbyen, Svalbard",
        "Norway",
        78.2232,
        15.6267,
        "Arctic/Longyearbyen",
        "The furthest north here. Polar night from late October, midnight sun from late April.",
    ),
    Place(
        "santorini",
        "Oia, Santorini",
        "Greece",
        36.4618,
        25.3753,
        "Europe/Athens",
        "The caldera faces west, which is why the sunset is the event.",
    ),
    Place(
        "banff",
        "Moraine Lake, Banff",
        "Canada",
        51.3217,
        -116.1860,
        "America/Edmonton",
        "First light hits the peaks well before it reaches the water.",
    ),
    Place(
        "torres",
        "Torres del Paine",
        "Chile",
        -50.9423,
        -73.4068,
        "America/Santiago",
        "Southern latitude, so the seasons invert.",
    ),
    Place(
        "teide",
        "Mount Teide, Tenerife",
        "Spain",
        28.2716,
        -16.6425,
        "Atlantic/Canary",
        "Often above the cloud layer, so the sun sets into cloud rather than sea.",
    ),
    Place(
        "barcelona",
        "Barcelona",
        "Spain",
        41.3874,
        2.1686,
        "Europe/Madrid",
        "The Eixample grid is rotated off the compass, so the light runs down the streets twice a year.",
    ),
    Place(
        "kirkjufell",
        "Kirkjufell",
        "Iceland",
        64.9271,
        -23.3075,
        "Atlantic/Reykjavik",
        "Just south of the Arctic Circle, so twilight lasts most of the night in summer.",
    ),
    Place(
        "tre-cime",
        "Tre Cime di Lavaredo",
        "Italy",
        46.6183,
        12.3033,
        "Europe/Rome",
        "The north faces catch alpenglow after the valley has gone dark.",
    ),
    Place(
        "sossusvlei",
        "Sossusvlei",
        "Namibia",
        -24.7272,
        15.3444,
        "Africa/Windhoek",
        "Low sun rakes the dunes, so the shape is only there for the first and last hour.",
    ),
    Place(
        "uluru",
        "Uluru",
        "Australia",
        -25.3444,
        131.0369,
        "Australia/Darwin",
        "The rock reddens as the sun drops, and the colour is gone within minutes.",
    ),
    Place(
        "atacama",
        "San Pedro de Atacama",
        "Chile",
        -22.9087,
        -68.1997,
        "America/Santiago",
        "The driest desert on earth, so twilight is unusually clean.",
    ),
    Place(
        "monrovia",
        "Monrovia",
        "Liberia",
        6.3005,
        -10.7969,
        "Africa/Monrovia",
        "Six degrees off the equator, so the day barely changes length all year.",
    ),
    Place(
        "mauna-kea",
        "Mauna Kea",
        "United States",
        19.8207,
        -155.4681,
        "Pacific/Honolulu",
        "Above 40 percent of the atmosphere, which is why the observatories are here.",
    ),
    Place(
        "petra",
        "Petra",
        "Jordan",
        30.3285,
        35.4444,
        "Asia/Amman",
        "Desert air and sandstone that only turns red for the first and last hour.",
    ),
    Place(
        "cape-town",
        "Cape Town",
        "South Africa",
        -33.9249,
        18.4241,
        "Africa/Johannesburg",
        "Table Mountain faces north, so the light crosses the face rather than hitting it.",
    ),
    Place(
        "aoraki",
        "Aoraki, Mount Cook",
        "New Zealand",
        -43.7340,
        170.0960,
        "Pacific/Auckland",
        "Inside a dark sky reserve, and far enough south for long winter nights.",
    ),
    Place(
        "ushuaia",
        "Ushuaia",
        "Argentina",
        -54.8019,
        -68.3030,
        "America/Argentina/Ushuaia",
        "The southern answer to Tromso. Long summer twilight, and barely seven hours of June daylight.",
    ),
    Place(
        "kyoto",
        "Kyoto",
        "Japan",
        35.0116,
        135.7681,
        "Asia/Tokyo",
        "Temple roofs, rivers, and wooded hills offer different horizons around the city.",
    ),
    Place(
        "fuji",
        "Lake Kawaguchi, Mount Fuji",
        "Japan",
        35.5171,
        138.7518,
        "Asia/Tokyo",
        "A lakeside view of Mount Fuji, with a mountain horizon that can hide the low Sun.",
    ),
    Place(
        "bromo",
        "Mount Bromo",
        "Indonesia",
        -7.9425,
        112.953,
        "Asia/Jakarta",
        "Volcanic ridges and a broad caldera create layered silhouettes in low light.",
    ),
    Place(
        "wadi-rum",
        "Wadi Rum",
        "Jordan",
        29.575,
        35.421,
        "Asia/Amman",
        "Sandstone towers frame wide desert horizons.",
    ),
    Place(
        "cappadocia",
        "Göreme, Cappadocia",
        "Türkiye",
        38.6431,
        34.8289,
        "Europe/Istanbul",
        "Soft volcanic rock and valleys cast long shadows around sunrise and sunset.",
    ),
    Place(
        "uyuni",
        "Salar de Uyuni",
        "Bolivia",
        -20.1338,
        -67.4891,
        "America/La_Paz",
        "The salt flat offers an open horizon; standing water can reflect the sky.",
    ),
    Place(
        "machu-picchu",
        "Machu Picchu",
        "Peru",
        -13.1631,
        -72.545,
        "America/Lima",
        "High mountain ridges shape the view, so visible sunlight can differ from the ideal horizon.",
    ),
    Place(
        "yosemite",
        "Yosemite Valley",
        "United States",
        37.7456,
        -119.5936,
        "America/Los_Angeles",
        "Granite cliffs catch light while the valley floor can already be in shade.",
    ),
    Place(
        "grand-canyon",
        "Grand Canyon, South Rim",
        "United States",
        36.0594,
        -112.109,
        "America/Phoenix",
        "A wide canyon reveals layers of rock as low sunlight moves across its walls.",
    ),
    Place(
        "joshua-tree",
        "Joshua Tree",
        "United States",
        33.8734,
        -115.901,
        "America/Los_Angeles",
        "Desert boulders and Joshua trees make strong silhouettes beneath an open sky.",
    ),
    Place(
        "tekapo",
        "Lake Tekapo",
        "New Zealand",
        -44.0047,
        170.4771,
        "Pacific/Auckland",
        "A lakeside perspective in the Aoraki Mackenzie International Dark Sky Reserve.",
    ),
    Place(
        "milford",
        "Milford Sound",
        "New Zealand",
        -44.6717,
        167.9256,
        "Pacific/Auckland",
        "Steep fjord walls rise above the water and obscure parts of the astronomical horizon.",
    ),
    Place(
        "abisko",
        "Abisko",
        "Sweden",
        68.3495,
        18.8312,
        "Europe/Stockholm",
        "An Arctic landscape beside Lake Torneträsk, with long seasonal changes in daylight.",
    ),
    Place(
        "la-palma",
        "Roque de los Muchachos",
        "Spain",
        28.754,
        -17.885,
        "Atlantic/Canary",
        "A high volcanic ridge on La Palma, home to astronomical observatories.",
    ),
)

BY_SLUG = {p.slug: p for p in PLACES}
